<a href="https://colab.research.google.com/github/Hyrysake/My_Data_Science/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vector = np.arange(1, 11)
print("1. Вектор:", vector)

1. Вектор: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
matrix_zeros = np.zeros((3, 3))
print("\n2. Матриця з нулями:\n", matrix_zeros)


2. Матриця з нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
matrix_random_integers = np.random.randint(1, 11, (5, 5))
print("\n3. Матриця з випадковими цілими числами:\n", matrix_random_integers)


3. Матриця з випадковими цілими числами:
 [[ 6  1  4  4  6]
 [ 5  7  9  7 10]
 [ 5  3  4  6  5]
 [ 4  8  9  2  6]
 [ 6  9  7  4  3]]


In [ ]:
matrix_random_floats = np.random.rand(4, 4)
print("\n4. Матриця з випадковими дійсними числами:\n", matrix_random_floats)


4. Матриця з випадковими дійсними числами:
 [[0.41112528 0.03426232 0.22315811 0.15716622]
 [0.46323775 0.391963   0.47820532 0.46065337]
 [0.06997922 0.50651508 0.24907538 0.3596842 ]
 [0.56882084 0.33938818 0.41663502 0.08073517]]


In [ ]:
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)
print("\n5. Елементні операції:")
print("   Додавання:", array1 + array2)
print("   Віднімання:", array1 - array2)
print("   Множення:", array1 * array2)


5. Елементні операції:
   Додавання: [6 3 7 9 8]
   Віднімання: [ 2  1  1  3 -6]
   Множення: [ 8  2 12 18  7]


In [ ]:
vector1 = np.random.random(7)
vector2 = np.random.random(7)
scalar_product = np.dot(vector1, vector2)
print("\n6. Скалярний добуток двох векторів:", scalar_product)


6. Скалярний добуток двох векторів: 1.6024904333687675


In [ ]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))
matrix_product = np.dot(matrix1, matrix2)
print("\n7. Добуток двох матриць:\n", matrix_product)


7. Добуток двох матриць:
 [[ 37 107 100]
 [ 24  74  52]]


In [ ]:
matrix_3x3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print("\n8. Обернена матриця:\n", inverse_matrix)


8. Обернена матриця:
 [[-0.14893617 -0.12765957  0.34042553]
 [ 0.08510638  0.28723404 -0.26595745]
 [ 0.14893617 -0.37234043  0.15957447]]


In [ ]:
matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix_4x4)
print("\n9. Транспонована матриця:\n", transposed_matrix)


9. Транспонована матриця:
 [[0.13737435 0.48674291 0.7404666  0.229508  ]
 [0.28038722 0.76309804 0.74730713 0.14169466]
 [0.99353606 0.18964337 0.76775619 0.08397984]
 [0.1319939  0.85008375 0.56489235 0.94870468]]


In [ ]:
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)
result = np.dot(matrix_3x4, vector_4)
print("\n10. Результат множення матриці на вектор:\n", result)


10. Результат множення матриці на вектор:
 [ 95  74 124]


In [ ]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
result = np.dot(matrix_2x3, vector_3)
print("\n11. Результат множення матриці на вектор:\n", result)


11. Результат множення матриці на вектор:
 [0.27836226 0.45252507]


In [ ]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
elementwise_product = np.multiply(matrix1, matrix2)
print("\n12. Поелементне множення двох матриць:\n", elementwise_product)


12. Поелементне множення двох матриць:
 [[42 27]
 [40  5]]


In [ ]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
matrix_product = np.dot(matrix1, matrix2)
print("\n13. Добуток двох матриць:\n", matrix_product)


13. Добуток двох матриць:
 [[95 34]
 [39 28]]


In [ ]:
matrix_5x5 = np.random.randint(1, 101, (5, 5))
sum_of_elements = np.sum(matrix_5x5)
print("\n14. Сума елементів матриці:\n", sum_of_elements)


14. Сума елементів матриці:
 1348


In [ ]:
matrix1_15 = np.random.randint(1, 11, (4, 4))
matrix2_15 = np.random.randint(1, 11, (4, 4))
difference_matrix = matrix1_15 - matrix2_15
print("\n15. Різниця двох матриць:\n", difference_matrix)


15. Різниця двох матриць:
 [[-6  4  3 -7]
 [-3 -1 -7 -1]
 [ 2 -1 -6 -1]
 [-8  7 -9 -2]]


In [ ]:
matrix_16 = np.random.rand(3, 3)
row_sums_vector = np.sum(matrix_16, axis=1)
column_vector = row_sums_vector.reshape(3, 1)
print("\n16. Вектор-стовпчик сум елементів кожного рядка матриці:\n", column_vector)


16. Вектор-стовпчик сум елементів кожного рядка матриці:
 [[1.69892807]
 [1.3326563 ]
 [2.08301167]]


In [ ]:
matrix_17 = np.random.randint(1, 11, (3, 4))
squares_matrix = np.square(matrix_17)
print("\n17. Матриця з квадратами чисел:\n", squares_matrix)


17. Матриця з квадратами чисел:
 [[ 1  1 16 16]
 [49 64 49  4]
 [ 4 49 49  1]]


In [ ]:
vector_18 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector_18)
print("\n18. Вектор з квадратними коренями чисел:\n", sqrt_vector)


18. Вектор з квадратними коренями чисел:
 [1.41421356 6.63324958 2.44948974 4.        ]
